version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env  # Charger les variables d'environnement depuis .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: myapp/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
